### ISSUE TITLE
数据内容问题

### ISSUE THREAD

**Issue by Jaren1907** [BAAI-Zlab/COIG#2]
您好，感谢您发布的数据集！
我在查看时发现 人类价值取向数据 `human_value_alignment_instructions_part2.json` 内容与 考试数据 `exam_instructions.jsonl` 内容格式一致，但与`human_*_part1.json`几乎毫不相干
请问是数据文件命名错误所致还是文件内容填充错误呢，谢谢

**Comment by shiyemin** [comment]
Both of them came from exam data. We divided them into different subset based on usage.
